### ISSUE TITLE
Error compiling the example code

### ISSUE THREAD

**Issue by marius** [kstep/cronparse.rs#3]
Hi,

when I try to compile the example code from the README I get

<pre>
src/main.rs:9:26: 9:31 error: the trait `core::fmt::Debug` is not implemented for the type `cronparse::CrontabFile<cronparse::crontab::UserCrontabEntry>` [E0277]
src/main.rs:9         println!("{:?}", entry);
                                       ^~~~~
<std macros>:2:25: 2:56 note: in this expansion of format_args!
<std macros>:3:1: 3:54 note: in this expansion of print! (defined in <std macros>)
src/main.rs:9:9: 9:33 note: in this expansion of println! (defined in <std macros>)
src/main.rs:9:26: 9:31 help: run `rustc --explain E0277` to see a detailed explanation
src/main.rs:9:26: 9:31 note: `cronparse::CrontabFile<cronparse::crontab::UserCrontabEntry>` cannot be formatted using `:?`; if it is defined in your crate, add `#[derive(Debug)]` or manually implement it
src/main.rs:9:26: 9:31 note: required by `core::fmt::Debug::fmt`
error: aborting due to previous error
</pre>

**Comment by kstep** [comment]
Thank you for pointing the bug out!
