### ISSUE TITLE
Add new entries

### ISSUE THREAD

**Issue by cholcombe973** [kstep/cronparse.rs#4]
This library looks great!  I'm trying to figure out how I would add new entries to a crontab and then write the resulting struct back out to the filesystem.  I think the CrontabFile struct needs an add_entry() function unless there's something in the library that already does this?

**Comment by kstep** [comment]
Actually, the library was created for the https://github.com/systemd-cron/systemd-cron-next project and can only read and parse crontab files. You are free to make a PR for the functionality you want, of course.

**Comment by cholcombe973** [comment]
I see.  No problem I'll put up a PR when i have some time.  Thanks!
